### ISSUE TITLE
Add device fails

### ISSUE THREAD

**Issue by JohanScheepers** [Snapp-X/snapp_cli#40]
Adding a new device fails. 

I can ran snapp_cli devices add,  snapp-cli bootstrap -v or snapp-cli bootstrap.

**Error:**
C:\Users\Johan>snapp_cli devices add

[WARN] Add command is a way to add a new device to custom devices manually.

We recommend you to use the bootstrap command to setup a device from scratch.

You need to provide specific PATH to the custom embedder you want to use.

✔ Please select the type of device you want to setup. · Express (recommended)

✔ Select your device · Raspberry Pi 4 Model B
Could not load custom device from config index 0: Expected enabled to be a boolean.

**_Environment:_**
Windows 10

Flutter 3.24.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4cf269e36d (8 days ago) • 2024-09-03 14:30:00 -0700
Engine • revision a6bd3f1de1
Tools • Dart 3.5.2 • DevTools 2.37.2

snapp-cli were installed today

**Comment by payam-zahedi** [comment]
Hey @JohanScheepers 

Thanks for opening this issue 

I'll try to take a look at this issue ASAP.

**Comment by payam-zahedi** [comment]
It seems the problem is related to your `custom_devices.json` file and the custom devices configured there.

Let's check several things together:

1. **Verify Administrator Privileges**

   Ensure that your Windows user account has administrator privileges to modify Flutter SDK files. Alternatively, you can run your CLI as an administrator. Make sure you have permission to read and write administrative files.

2. **Enable Custom Device Configuration**

   Confirm that the custom device configuration is enabled in your Flutter SDK. You can check this by running:

   ```bash
   flutter config --list
   ```
   The output should resemble:
   ``` yaml
   All Settings:
      enable-web: (Not set)
      enable-linux-desktop: true
      enable-macos-desktop: (Not set)
      enable-windows-desktop: (Not set)
      enable-android: true
      enable-ios: (Not set)
      enable-fuchsia: (Not set) (Unavailable)
      enable-custom-devices: true
      cli-animations: (Not set)
      enable-native-assets: (Not set) (Unavailable)
      enable-flutter-preview: (Not set) (Unavailable)
      enable-swift-package-manager: (Not set) (Unavailable)
   ```
   If `enable-custom-devices` is not enabled, you can enable it with the following command:
   ``` bash
   flutter config --enable-custom-device
   ```
3. **Inspect** `custom_devices.json` **File**
    Check your `custom_devices.json` file for any issues, such as **syntax** errors. Consider making a **backup** of this file, then empty its contents, and run the command again to see if the problem persists.
